# Generated by Django 4.0.6 on 2022-07-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Idea name')),
                ('about', models.TextField(verbose_name='Idea about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Idea image')),
            ],
            options={
                'verbose_name': 'TourIdea',
                'verbose_name_plural': 'TourIdeas',
            },
        ),
    ]
