# Generated by Django 4.0.6 on 2022-07-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_about_name1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='name1',
            field=models.TextField(verbose_name='About name1'),
        ),
    ]
