# Generated by Django 4.0.6 on 2022-07-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_about_name1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mezhet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='mezh name')),
                ('about', models.TextField(verbose_name='mezh about')),
                ('img', models.ImageField(upload_to='media', verbose_name='mezh image')),
            ],
            options={
                'verbose_name': 'Mezhet',
                'verbose_name_plural': 'Mezhets',
            },
        ),
    ]
