# Generated by Django 4.0.6 on 2022-07-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_blogbg_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogbg',
            name='name',
            field=models.CharField(max_length=50, verbose_name='blogbg name'),
        ),
    ]
