# Generated by Django 4.0.6 on 2022-07-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_blogbg_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karciqner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='vayr name')),
                ('about', models.TextField(verbose_name='vayr about')),
                ('img', models.ImageField(upload_to='media', verbose_name='vayr image')),
            ],
            options={
                'verbose_name': 'Karciqner',
                'verbose_name_plural': 'Karciqners',
            },
        ),
    ]
