# Generated by Django 4.0.6 on 2022-07-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_karciqner_name_karciqner_name1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staysmax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='stays name')),
                ('name2', models.IntegerField(verbose_name='stays name')),
                ('name3', models.IntegerField(verbose_name='stays name')),
                ('name4', models.IntegerField(verbose_name='stays name')),
                ('name5', models.IntegerField(verbose_name='stays name')),
            ],
            options={
                'verbose_name': 'Staysmax',
                'verbose_name_plural': 'Staysmaxs',
            },
        ),
        migrations.CreateModel(
            name='Staysmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='stays name')),
                ('name2', models.IntegerField(verbose_name='stays name')),
                ('name3', models.IntegerField(verbose_name='stays name')),
                ('name4', models.IntegerField(verbose_name='stays name')),
                ('name5', models.IntegerField(verbose_name='stays name')),
            ],
            options={
                'verbose_name': 'Staysmin',
                'verbose_name_plural': 'Staysmins',
            },
        ),
    ]
