# Generated by Django 4.0.6 on 2022-07-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_staysmax_staysmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staysmax',
            name='name',
            field=models.IntegerField(verbose_name='staysx name1'),
        ),
        migrations.AlterField(
            model_name='staysmax',
            name='name2',
            field=models.IntegerField(verbose_name='staysx name2'),
        ),
        migrations.AlterField(
            model_name='staysmax',
            name='name3',
            field=models.IntegerField(verbose_name='staysx name3'),
        ),
        migrations.AlterField(
            model_name='staysmax',
            name='name4',
            field=models.IntegerField(verbose_name='staysx name4'),
        ),
        migrations.AlterField(
            model_name='staysmax',
            name='name5',
            field=models.IntegerField(verbose_name='staysx name5'),
        ),
        migrations.AlterField(
            model_name='staysmin',
            name='name2',
            field=models.IntegerField(verbose_name='stays name1'),
        ),
        migrations.AlterField(
            model_name='staysmin',
            name='name3',
            field=models.IntegerField(verbose_name='stays name2'),
        ),
        migrations.AlterField(
            model_name='staysmin',
            name='name4',
            field=models.IntegerField(verbose_name='stays name3'),
        ),
        migrations.AlterField(
            model_name='staysmin',
            name='name5',
            field=models.IntegerField(verbose_name='stays name4'),
        ),
    ]
