# Generated by Django 4.0.6 on 2022-07-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_staysmin_name_alter_staysmin_name2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaysHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(choices=[('P', 'Plaza'), ('C', 'Continental'), ('R', 'Russia')], default='R', max_length=1)),
            ],
            options={
                'verbose_name': 'StaysHotel',
                'verbose_name_plural': 'StaysHotels',
            },
        ),
    ]
