# Generated by Django 4.0.6 on 2022-07-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_stayshotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aminit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='aminites name')),
                ('name2', models.CharField(max_length=30, verbose_name='aminites name2')),
                ('name3', models.CharField(max_length=30, verbose_name='aminites name3')),
                ('name4', models.CharField(max_length=30, verbose_name='aminites name4')),
                ('name5', models.CharField(max_length=30, verbose_name='aminites name5')),
            ],
            options={
                'verbose_name': 'Aminit',
                'verbose_name_plural': 'Aminits',
            },
        ),
        migrations.CreateModel(
            name='BHK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='BHK')),
                ('name2', models.IntegerField(verbose_name='BHK2')),
                ('name3', models.IntegerField(verbose_name='BHK3')),
                ('name4', models.IntegerField(verbose_name='BHK4')),
                ('name5', models.IntegerField(verbose_name='BHK5')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='property status')),
                ('name2', models.CharField(max_length=30, verbose_name='property status2')),
                ('name3', models.CharField(max_length=30, verbose_name='property status3')),
                ('name4', models.CharField(max_length=30, verbose_name='property status4')),
                ('name5', models.CharField(max_length=30, verbose_name='property status5')),
            ],
            options={
                'verbose_name': 'PropertyST',
                'verbose_name_plural': 'PropertySTs',
            },
        ),
        migrations.CreateModel(
            name='PropertyTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='property type')),
                ('name2', models.CharField(max_length=30, verbose_name='property type2')),
                ('name3', models.CharField(max_length=30, verbose_name='property type3')),
                ('name4', models.CharField(max_length=30, verbose_name='property type4')),
                ('name5', models.CharField(max_length=30, verbose_name='property type5')),
            ],
            options={
                'verbose_name': 'PropertyTyp',
                'verbose_name_plural': 'PropertyTyps',
            },
        ),
        migrations.DeleteModel(
            name='StaysHotel',
        ),
    ]
