# Generated by Django 4.0.6 on 2022-07-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_aminit_bhk_propertyst_propertytyp_delete_stayshotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='Bathroom')),
                ('name2', models.IntegerField(verbose_name='Bathroom2')),
                ('name3', models.IntegerField(verbose_name='Bathroom3')),
                ('name4', models.IntegerField(verbose_name='Bathroom4')),
                ('name5', models.IntegerField(verbose_name='Bathroom5')),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='Bedroom')),
                ('name2', models.IntegerField(verbose_name='Bedroom2')),
                ('name3', models.IntegerField(verbose_name='Bedroom3')),
                ('name4', models.IntegerField(verbose_name='Bedroom4')),
                ('name5', models.IntegerField(verbose_name='Bedroom5')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Services name')),
                ('text', models.TextField(verbose_name='Services text')),
                ('img', models.ImageField(upload_to='media', verbose_name='Services img')),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Servicess',
            },
        ),
    ]
