# Generated by Django 4.0.6 on 2022-07-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_bathroom_bedroom_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='flights name')),
                ('name2', models.CharField(max_length=20, verbose_name='flights name2')),
                ('name3', models.CharField(max_length=20, verbose_name='flights name3')),
            ],
            options={
                'verbose_name': 'Flights',
                'verbose_name_plural': 'Flightss',
            },
        ),
    ]
