# Generated by Django 4.0.6 on 2022-07-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_flights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flightspay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='flights name')),
            ],
            options={
                'verbose_name': 'Flightspay',
                'verbose_name_plural': 'Flightspays',
            },
        ),
        migrations.AddField(
            model_name='flights',
            name='name4',
            field=models.CharField(max_length=20, null=True, verbose_name='flights name2'),
        ),
        migrations.AddField(
            model_name='flights',
            name='name5',
            field=models.CharField(max_length=20, null=True, verbose_name='flights name3'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='name2',
            field=models.CharField(max_length=20, null=True, verbose_name='flights name2'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='name3',
            field=models.CharField(max_length=20, null=True, verbose_name='flights name3'),
        ),
    ]
