# Generated by Django 4.0.6 on 2022-07-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_flightspay_name2_flightspay_name3_flightspay_name4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='name5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='flights name5'),
        ),
    ]
