# Generated by Django 4.0.6 on 2022-07-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_flights_name5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flightsrec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='flightsrec name')),
                ('name2', models.CharField(max_length=20, null=True, verbose_name='flightsrec name2')),
            ],
            options={
                'verbose_name': 'Flightsrec',
                'verbose_name_plural': 'Flightsrecs',
            },
        ),
    ]
