# Generated by Django 4.0.6 on 2022-07-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_flightsrec'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaysHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='hotek name')),
                ('rennt', models.CharField(choices=[('R', 'for Rent'), ('S', 'for Shell')], default='R', max_length=1)),
                ('img', models.ImageField(upload_to='media', verbose_name='hyuranosc nakar')),
                ('pay', models.IntegerField(verbose_name='pay')),
                ('sqft', models.IntegerField(verbose_name='sqrft chap')),
                ('beds', models.IntegerField(verbose_name='beds')),
                ('bats', models.IntegerField(verbose_name='bets')),
                ('photo', models.IntegerField(verbose_name='photo')),
                ('video', models.IntegerField(verbose_name='video')),
            ],
            options={
                'verbose_name': 'StaysHotel',
                'verbose_name_plural': 'StaysHotels',
            },
        ),
    ]
